### ISSUE TITLE
動作方法確立記録

### ISSUE THREAD

**Issue by forno** [agrirobo/arcsys2#13]
我々３回生はログが残る会議より、ログが残らない話し合いのほうが有意義で意味があり、効果が上がる内容を行うことが多い。

しかし、ログは残したい。
そんなわけで、変動のまっただ中、下手にソフトを触れない間だけでもなぐり書きログを残したい。

じゃけん @YamaCIR-KIT さんログ残しおねがいします。

**Comment by yamacir-kit** [comment]
具体的にどの範囲のログ？
今年の開発の流れの思い出話でも書いておけばいいのか，初めからこうしておけばよかった系統の教訓を書き並べればいいのか

**Comment by forno** [comment]
ログって言ってるから今からでいいのです。　そのurdfのお話でもちょっとメモってなさい。

**Comment by yamacir-kit** [comment]
まずはじめに書くべきはurdfないしはxacroファイルであったと思う
ソフト班もハード班も顔を突き合わせてまずこれを完成させるところからやっときゃよかった
それとハード班から各種パラメータを要求しないと引き出せないのも（しても出てこないけど）大分困る

**Comment by yamacir-kit** [comment]
というよりソフトとハードでバッサリ二分したのが最もダメだったかもしれぬ
モジュールを人数分に分割したほうが良かったのではないかとも思う
しかしまあ特化していなかったらここまでの知識をこの期間で得られたかと言われれば無理なわけだけど

**Comment by forno** [comment]
まあ、うちとしてはふたり組での開発というものが効果を上げるんじゃないかと考えていて、その点で言うと俺とお前の組はなかなかに良かったんではなかろうかと思う。

**Comment by yamacir-kit** [comment]
ツーマンセル行動は義務付けてもいいくらいだと思う
ソフト班は予定通りに行かなかったところもあるけど、それ以上にgithubでの運用が威力を発揮してまとまってる感はあると思う

あとはコンセプト逸脱とかが起こらないように注意を払わないといけない
今回はぎりぎりのところで修正できたけど、マネージャー職を置かない以上、進捗含めて相互監視ができてない現状はヤバい

**Comment by yamacir-kit** [comment]
しかしまあ率直に言って今年のハードは詰みかけてるんじゃないか
自分の足を使って直接買い付けに行って自腹切らないともう間に合わない域にあると思われ

**Comment by yamacir-kit** [comment]
引き継ぎに向けて開発・勉強手順的なのをテキストにまとめてるんだが
GistにアップするのとLaTeXで書きなおしてPDFで配るのとどっちが良いかね

**Comment by forno** [comment]
一応書類作って先代から使われなくなってしまったファイルにファイリングしておいてやりなー。

**Comment by forno** [comment]
Git flowが不全だったので Github flow に切り替えて運用開始

**Comment by forno** [comment]
RobotHWとジョイント周りの連携が取れぬ。つらたん。

**Comment by forno** [comment]
Moveitの攻略に時間がかかる。

**Comment by yamacir-kit** [comment]
MoveIt攻略記念

**Comment by forno** [comment]
RobotHWハック記念

**Comment by yasu80** [comment]
Raspi_3 ROS稼働記念
wifi未稼働
[Imageが落ちてたところ](https://wiki.ubuntu.com/ARM/RaspberryPi#Optional_PPA)
[wifi死んでる対策(自分用にほしい・・・)](http://www.yodobashi.com/ec/product/100000001002821926/index.html?gad1=&gad2=g&gad3=&gad4=56278881131&gad5=4321577490127942333&gad6=1o1&xfr=pla&gclid=CImGhar019ACFYuUvQodshQPRQ)

**Comment by forno** [comment]
@yasu80 のリンク切れをこっそり直しました(こっそり)

**Comment by yasu80** [comment]
@forno あっ・・・(ありがとうございます)

**Comment by yasu80** [comment]
うえで貼ったリンクの奴, デフォだとレポジトリがゴミなのでぶち殺して
[これ](http://wiki.ros.org/kinetic/Installation/Ubuntu)
にしました.

**Comment by yasu80** [comment]
そうすると, 本家のros-kinetic-なんとか が使えるようになって便利になりました
ぶっちゃけ今まで使ってたPCと同等かそれ以上に実行素早くて悲しくなります

build & 実行できた記念(いいテスト項目が見つからないけれど, とにかくarcsys2ビルドして適当なlaunch とか呼べることだけわかったからいいや)

**Comment by yasu80** [comment]
gpio/wiringPi入った記念
動いてるみたいだけれど回路がない, 工房で確認するよん

しっかし冗談半分で口にしたPi3導入やっちゃいましたね・・・

**Comment by yamacir-kit** [comment]
動いたようで何より
@fornoはドライバ周りでどこを手伝えばいいか教えてくれ

**Comment by forno** [comment]
今後RobotHWを位置制御に組み替える。
位置制御情報は、`geometry_msgs/Point` でxに直線移動位置が指示される。
ドライバは自分で保有してる現在位置から指示点までの回転量を自前で計算して、そこへ移動する。
現在位置は`sensor_msgs/Odometry` の位置xを用いて吐く。

これをジョイント名と同じ名前空間の`pose` topic と `odom` トピックに吐くようにする
```
joint_name/cmd_pos : geometry_msgs/Point
joint_name/odom  : sensor_msgs/Odometry
```

なお、回転量を計算する件でタイヤ半径が必要になるので、そこはパラメータで与えられるようにする。また、制御に使用するピン番号もパラメータで与える。

これにより2つのモータの制御を同一のプログラムで行える予定。

**Comment by yasu80** [comment]
Pi3:本番用の小形ルータでローカルネットワーク形成を確認し, ssh接続まで確認.
※本校の Network はどうも改変があったらしく, Pingを通せなくなっています. 注意.

**Comment by shimoe** [comment]
@forno です．パソコンが粉微塵になったのでシモエのアカウント借りてます．

昨年使用した普通のトランジスタが規定数ありましたので， @yasu80 は普通にraspberry-pi のコードを書いてくださいまし．トランジスタはトランジスタ入れの中に戻しておくので， @forno か @shimoe まで場所を聞いてください．

データシートはコレのGR版です． http://akizukidenshi.com/download/2sc1815-gr.pdf
引き続き開発を進めてゆきましょう．

**Comment by yamacir-kit** [comment]
@forno かよ
ついに @shimoe もissue参戦かとワクワクしながら開いた俺の期待返せや

**Comment by yasu80** [comment]
@shimoe  @forno 了解です. とりあえず作れるところで,
Twist → パルス信号
スピード信号 → joint_name/odom
みたいな感じで行きます.

**Comment by yasu80** [comment]
>なお、回転量を計算する件でタイヤ半径が必要になるので、そこはパラメータで与えられるようにする。また、制御に使用するピン番号もパラメータで与える。

わかりました.

>なお、回転量を計算する件でタイヤ半径が必要になるので、そこはパラメータで与えられるようにする。また、制御に使用するピン番号もパラメータで与える。

タイヤどれくらい滑るかとかは実地検証ですね...

>これをジョイント名と同じ名前空間

ちょっとこの辺手こずりそうです.

**Comment by forno** [comment]
@yasu80 
一応補足しておくと，うちが使ってるドライバはstart信号を流すと設定した回転方向に回るタイプです．
パルス信号は生成する必要がありません．

あと指令値の仕様が変わったので，TwistではなくPointの位置指令になってます，その点よろしくです．

Odomについては，ドライバから得られるSPEEDパルス信号を，タイヤ半径を考慮して直線移動距離に直してOdomを生成してください．よろしくお願いします．

仕様を再掲します

```
joint_name/cmd_pos : geometry_msgs/Point : 位置指令
joint_name/odom  : sensor_msgs/Odometry : 現在位置
```

あと足のタイヤが滑るという事象は普通無視できるものだと思います，また，システムの構成上，今回はほぼ考慮する必要がありません．
垂直移動部は滑らない構造をしているのでこちらも考えるひつようはないです．

ドライバ作製よろしくお願いします．

**Comment by forno** [comment]
いい忘れましたが，回路設計は済んでいるので回路を組む人を募集中です．
@yasu80 はプログラム作製に集中してて大丈夫です．その点は最悪ブレッドボードでもいけますので．

**Comment by yasu80** [comment]
@forno 了解しました.

**Comment by forno** [comment]
作業お疲れ様やで(激遅
