### ISSUE TITLE
RobotHWをMovit!に接続したい

### ISSUE THREAD

**Issue by forno** [agrirobo/arcsys2#26]
タイトルのように、Moveit!にRobotHWを認識させる方法を探しています。

RobotHWのサンプルは書けたかと思うので、あとはコントローラとRobotHWを結びつければ動くとは思うのですが、ジョイントコントローラ、コントローラ、ジョイントpub,ロボットステートpubなどなどがどうすればきちんと動作するのか思うようにわからず、時間だけが過ぎてゆきます。

どなたか、助言やプルリクをいただけますと助かります。

**Comment by yamacir-kit** [comment]
#31 
出来ました

この時点で
`rosrun arcsys2_controller arcsys2_controller_node __ns:=/arcsys2_controller`
`roslaunch arcsys2_bringup arcsys2_bringup_moveit.launch`
`roslaunch arcsys2_bringup arcsys2_bringup_controller.launch`
を順に実行することでMoveItからの軌道計算結果が各RobotHWに送られるようになります

C++コードから目標geometry_msgs::Poseへの軌道計算，および実行は
`rosrun arcsys2_move_group_interface arcsys2_move_group_interface_node`
で（規定値のPoseで二度軌道計算するだけですが）確かめられます

もちろんダミーのRobotHWしか実装していないので実行でタイムアウトしますが
