### ISSUE TITLE
やることリスト

### ISSUE THREAD

**Issue by yamacir-kit** [agrirobo/arcsys2#32]
残り二週間，やらなければいけないことを列挙して潰していきましょう

必須
- [x] 各アクチュエータのドライバおよびRobotHWの実装
- ~~最近接トマトに対するエンドエフェクタのPoseを出力するノードの実装~~ move_group_interface に内蔵
- ~~トマトの発見・未発見を監視しベースを移動させるノードの実装~~
- ~~初期姿勢，収穫カゴへの姿勢をプリセットとしてMoveItに設定~~
- ~~エンドエフェクタによる収穫動作の実装（MoveItへしかるべきPoseを吐き切断を行う）~~

オプション
- [ ] リネームを中心としたパッケージ，名前空間の整理
- [x] 不要となったgazebo関係の設定ファイルの掃除
- [ ] エンドエフェクタのトマト把持検知機構の実装

**Comment by forno** [comment]
すべてのアクチュエータ用の RobotHW (Control) を構成しました。
libics3はドライバまで実装済みです。
DCMotor用のドライバ開発をすすめる必要が有ります。

- [x] シャフト ドライバ
- [x] アーム0 ドライバ

面倒なのでおそらく両方共同一Arduinoに押し込むかもしれません。
ラズパイとROS通信できたら楽なんだけどなー(ﾁﾗﾁﾗｯ

**Comment by yasu80** [comment]
- [x] kinect_tomato_group_search についての画像規正
- [x] 上についての視覚補正(旧Kinect用の数字が入っている)
- [ ] 上についての画像明度, 彩度, ガンマその他調整機能
- [ ] kinect_tomtato_searcherのMATLAB関数の取り扱い統一他リファクタ

・・・を @forno  氏に託しました

**Comment by forno** [comment]
モータドライバとオドメトリ計算機の2段構成*2 (シャフトとarm0)
という構成で行きます。実装完了は水曜日までを予定。

**Comment by yamacir-kit** [comment]
個人毎のリストを書いているようなので俺もそれに合わせます
初めに書いたものからRobotHWの下りが@fornoの管轄になり，一連の収穫動作がmove_group_interfaceの役割にまとまりました
また，切断後のトマト収納がハードウェア的に実装されるので消えました

- [ ] tomato_point_rawの値をあまりに的はずれな座標でないことを保証した上でtomato_point_trustedとしてpublishするノードの実装
- [x] tomato_broadcasterの改良（tf周りの仕様が去年のままなので），tomato_point_trustedのbroadcast
- ~~tomato_point_trustedからPoseを出力するノードの実装~~
- [x] move_group_interfaceノードによるアプローチ，切断までの実装

moveitがsensorの取り扱いをサポートしており，controllerの設定と同じ要領で設定できそうなことがわかってきましたが，とりあえず汚めでも動くものを先に実装します

**Comment by yasu80** [comment]
@YamaCIR-KIT 
質問があります.
>tomato_point_rawの値をあまりに的はずれな座標でないことを保証した上でtomato_point_trustedとしてpublishするノードの実装

これってtomato_point_rawについて 最尤推定みたいなことをするって理解でいいでしょうか.

**Comment by forno** [comment]
broad caster にブロードキャストしてもらう前にtomato_point_rawの値をあまりに的はずれな座標でないことを保証した上でtomato_point_trustedにする処理をいれて、それをブロードキャストするようにしてもらっていいですか？

**Comment by yamacir-kit** [comment]
変更しました

@yasu80 
そこまで大掛かりなものではなくて，値がある程度の範囲で整定していること，アームのレンジ内であること（レンジ外の座標を放り込んでもどうせ失敗するのでいらないかも）が分かれば十分と考えています

**Comment by yasu80** [comment]
@YamaCIR-KIT 
わかりました.
手前のトマトと奥のトマトに照準を合わせた時で画像平面上で流れるスピードが違うって問題があるかな, と思ったんですけれど, トマトのある範囲に奥行きが(そんなに)ないことはだいたいわかっているので,  そんな心配なかったですね...
(もしその場合, トマトのある範囲にあわせて depth から 移動速度の適当な値を求める必要があり, それをやるのは画像処理の部分に合わせて良いのではと思っていた)

**Comment by yamacir-kit** [comment]
tomato_pointについて
tomato_point/raw
tomato_point/trusted
とする方向で話が（顔を突き合わせて話した結果）まとまりました

**Comment by forno** [comment]
tomato_pointについて
Poseを使用するようになったので構成を変更しました
- tomato_point/array : PoseArray
- tomato_point/raw : PoseStamped
- ~~tomato_point/trusted~~ : PoseStamped
こんな感じの構成です。

**Comment by yamacir-kit** [comment]
現状，思ったよりも誤差小さめでkinectからmoveitまでトマト座標が運べているので，`tomato_point/trusted`の実装を凍結して`tomato_point/raw`を直接ブロードキャストする方向で進めます（３日ほど前からそうしてるけど）

というか，当初計画していた`tomato_point/raw`に対する`tomato_point/trusted`の動作を，現在でいうところの`tomato_point/array`に対する`tomato_point/raw`が実現しているのでは？

**Comment by forno** [comment]
@YamaCIR-KIT 
現在そのような機能は一切入ってないです．
前回値に最も近いトマトポイントをひとつ選んでそれをそのまま転送してます．

**Comment by forno** [comment]
閉じます（白目）
