### ISSUE TITLE
planner(main_action_planner)の仕様決め

### ISSUE THREAD

**Issue by forno** [agrirobo/arcsys2#5]
現在main_action_plannerを作成中です。
この子の仕様を決めましょう。

現在、main_action_plannerにメインクロックを持たせて、
シークエンスを管理してもらい、
シークエンス別にserviceで別パッケージに姿勢を計算してもらい、
その結果を受け取って所定のトピックに吐くという構成を考えています。

意見があれば誰でも書き込んでください。

**Comment by yamacir-kit** [comment]
# 直接話して決めましょう

**Comment by forno** [comment]
議論を残すためにやってるんだよなぁ…(悪乗り)
なお、直接話しながらふざけてIssueしました。

**Comment by yasu80** [comment]
妙なことを聞きますが
→ メインクロックでシークエンス管理プロセスと他プロセスを同期管理 
→ メインクロックがシークエンス管理プロセスを管理, ほかプロセスはただのリスナー
前者は同期ズレがありうるので・・・後者ですよね
水晶発振子を持ったマイコン的なんかが脳内に浮かんでいます

**Comment by forno** [comment]
@yasu80 Yes! というよりむしろこいつ以外は元からただのリスナー設計ですぜ。

**Comment by AriYu** [comment]
状態管理のためのパッケージというかライブラリで[smach](http://wiki.ros.org/smach)というのがあるそうです。
私も使ったことはないのですが、便利そうなので紹介しておきます。
見当違いのことを言っていたらすいません。

**Comment by forno** [comment]
> 状態管理のためのパッケージというかライブラリでsmachというのがあるそうです。
> 私も使ったことはないのですが、便利そうなので紹介しておきます。
> 見当違いのことを言っていたらすいません。

紹介ありがとうございます。参考にします。

**Comment by forno** [comment]
お疲れ様です。内部状態を切り替える部分の設計がなかなか思いつかないので案を募集します。

**Comment by forno** [comment]
つまり状態移行条件の方針、指針、具体案などなどを考えて頂きたいです。
現在出てるのは、一定時間ごとに内部状態を変化させるという自立ロボット(?)みたいなやつです。

**Comment by yamacir-kit** [comment]
案が一つあるんだがうまく言語化出来ない

**Comment by yamacir-kit** [comment]
頑張って言語化してる

纏めたらgistとかにアップすればいいかな？
テキストファイルね

**Comment by yamacir-kit** [comment]
一人で考えてると頭が爆発しそうなのでとりあえず説明だけ書きなぐってアップしました
タスケテヘルプミー
https://gist.github.com/YamaCIR-KIT/783ae7ac1917ad980449c8a9c9369682

等幅フォントで見ないと崩れる

**Comment by yamacir-kit** [comment]
とりあえずブランチ切って上のやつ試してみる
無断でdevelopにマージするようなことはしないのでご安心を

**Comment by forno** [comment]
ステータスを更新する部分を別パッケージに分離して、依存関係を最小にしておくことにしました。
案出しありがとうございました。

**Comment by forno** [comment]
基礎設計が完了しプルリクエスト #10 が受理されました。
