### ISSUE TITLE
move_group_interface のエラー

### ISSUE THREAD

**Issue by forno** [agrirobo/arcsys2#61]
どうせ @YamaCIR-KIT が引きこもって報告するタイミングがなくなるから貼り付け

Moveit! のエラー
```bash
[ INFO] [1480849275.658671067]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1480849275.660365434]: No planner specified. Using default.
[ INFO] [1480849275.660767564]: RRTConnect: Starting planning with 1 states already in datastructure
[ERROR] [1480849280.662314325]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1480849280.662366419]: RRTConnect: Created 1 states (1 start + 0 goal)
[ INFO] [1480849280.662386893]: No solution found after 5.001715 seconds
[ INFO] [1480849280.688156526]: Unable to solve the planning problem
```

実験環境はsensorを除いたランチすべてで、dammyはtrueである。
直してね☆

**Comment by yamacir-kit** [comment]
それはアームの範囲外って事だゾ☆

**Comment by forno** [comment]
お前それ `dammy_tomato`に設定されている値見ても言えんの？

**Comment by yamacir-kit** [comment]
今はトマトの座標から0.1手前にもってくようにしてあるからそいつが悪さをしているのかもしれぬ
しかしそのエラーは「アームのレンジ外」ないしは「アームが6自由度を下回っている」以外で見たことがない

試してみる

**Comment by forno** [comment]
ちなみにだが、moveit用のlaunchを立ち上げる前にdammy_tomatoを流しておくと、上記エラーが定量的に得られた。という情報を置いておこう

**Comment by yamacir-kit** [comment]
分かった

スレチだけどbrigup_all.launchの各モジュールのdammy引数の名前が決まらない
dammy_controller:=true
とかだと冗長すぎる気がするんだがいい案ない？

**Comment by forno** [comment]
allなら `disable_sensor:=true` とかのモジュール切り離し機能がほしい。

ダミー起動は好きにしてクレメンス。でも別にそれでも十分いいと思うけどね。

**Comment by forno** [comment]
と思ったけど、やっぱりダミーで良かったのでその方針で良いと思われる。

**Comment by yamacir-kit** [comment]
直したので閉じます

**Comment by yamacir-kit** [comment]
直ってませんでした
#79 参照
