### ISSUE TITLE
dammy のスペルミスが有るので dummy にする

### ISSUE THREAD

**Issue by forno** [agrirobo/arcsys2#63]
dammyというスペルミスが有るので grep と sed と mv と bash拡張の{}構文 を用いて直していく予定。

他にやりたい人がいたらやってください。

**Comment by yamacir-kit** [comment]
やりたくない

**Comment by RyodoTanaka** [comment]
Close は違う．
https://www.youtube.com/watch?v=ut-522Wuokk

**Comment by forno** [comment]
#69 でやり終えたと思ってたら抜けがあったご様子。

#88 出しました。

**Comment by forno** [comment]
Completed!
