### ISSUE TITLE
moveitの仕様についてのあれこれ（続・move_group_interfaceのエラー）

### ISSUE THREAD

**Issue by yamacir-kit** [agrirobo/arcsys2#79]
タイトル自体は #61 を踏襲してこのようにしましたが，move_group_interfaceのエラーではありません
自分たちのロボットでmoveitのフロントエンドとして動かしているノード名がmove_group_interface_nodeであるため上記のようなissue名が付けられていますがmoveitにおいて本来move_group_interfaceと呼ばれているものは基本的に無罪です

問題はKRSサーボを実際に接続した場合，`moveit::planning_interface::MoveGtoup::plan()`には成功するものその後の`moveit::planning_interface::MoveGtoup::execute`に失敗するというもので，当該issueで予測していたようにtolerance由来の問題ではあるのですが，到達点のtoleranceではありませんでした

原因は`plan()`時にstart stateとして設定されたジョイント値と`execute()`時のジョイント値が食い違っていることによるもので，この差の許容値を設定するものが最近まで存在しなかったようです
これはロボットの能動的な関節の動作によるものではなく，受動的ないしはセンサの分解能的な値の変化（これ伝わるかな）なので，ロボット側で感知出来るものではないようです

俺達が使っているKRSサーボの場合，分解能的に0.01（rad？）はギリギリアウトくらいの値のようなので，仕方ないというのが結論です

（規定値として出てくる0.01という数字はマジックナンバーとして埋め込まれてたのかな？　解決優先でそのあたりの事情までは詳しくしらべていません）

moveit公式での問題提起は https://github.com/ros-planning/moveit/issues/283 でなされ https://github.com/ros-planning/moveit/pull/223 のマージで解決策が導入されたようですが流し読みしかしていないので詳しくはリンク先を呼んで下さい

なにやらリンク先では正規化だの言っていますがエライ人の話はよく分からんので手っ取り早い話，導入された`allowed_start_tolerance`（デフォルト値はやはり0.01）の変更が楽でしょう
`hoge_moveit_config/launch/trajectory_execution.launch.xml`にてparamで設定が行えるようです

しかしこの変更は日付を見て分かる通りここ一月ちょっとの話なので，まだaptでインストールできるバイナリには変更がまだ反映されてないようです（俺の`/opt/ros/indigo/include/moveit`内を洗ってみた所，該当コードは見つかりませんでした）

結局何が言いたいかというと，直すには最新ソースをコンパイルしないとダメみたいね

**Comment by yamacir-kit** [comment]
最新ソースからのmoveitリコンパイルの後，セットアップアシスタントによる設定ファイル再生成で`trajectory_execution.launch.xml`に`allowed_start_tolerance`が生成されたのを確認しました

インストールは`catkin_ws/src`にて以下を実行して行いました

```
sudo apt-get install python-wstool python-catkin-tools
wstool init .
wstool merge https://raw.githubusercontent.com/ros-planning/moveit/indigo-devel/moveit.rosinstall
wstool update
rosdep install --from-paths . --ignore-src --rosdistro indigo
cd ..
catkin config --extend /opt/ros/indigo --cmake-args -DCMAKE_BUILD_TYPE=Release
catkin build
```

**Comment by yamacir-kit** [comment]
最新のmoveitのバグというほどでも無いかもしれませんがひでぇ仕様があったので報告

従来のセットアップアシスタントで`moveit_config/launch/move_group.launch`に生成されていた以下の最重要コードが何故か生成されなくなっているので注意
move_groupノードへ渡すparamです
```
    <param name="capabilities" value="move_group/MoveGroupCartesianPathService
                                      move_group/MoveGroupExecuteService
                                      move_group/MoveGroupKinematicsService
                                      move_group/MoveGroupMoveAction
                                      move_group/MoveGroupPickPlaceAction
                                      move_group/MoveGroupPlanService
                                      move_group/MoveGroupQueryPlannersService
                                      move_group/MoveGroupStateValidationService
                                      move_group/MoveGroupGetPlanningSceneService
                                      move_group/ApplyPlanningSceneService
                                      move_group/ClearOctomapService
                                      " />
```

その代替と思しきコードが従来のmoveitにおいて上のコードが配されていた位置に生成されていますが，何をしているのか不明な上，初期状態でコメントアウトされているので保留

もしかしたら俺が阿呆なだけかもしれないが，実行もカーテシアンパスもアクションも何もかもセットアップアシスタントで生成されるコードではDisableになっている
解せぬ

**Comment by forno** [comment]
周知完了と判断しクローズ
