### ISSUE TITLE
命名則、コーディングスタイルその他

### ISSUE THREAD

**Issue by yamacir-kit** [agrirobo/arcsys2#9]
krs_servo の名称を今後追加されるであろう別種のサーボモータのために servo_krs としたいが、変更した場合どれくらい他のパッケージに影響があるかわからないから意見求む。
個人的には libics3 対応のためにどうせ全て書き換えることになるからこの機会に書き換えたい。

それと収拾がつかなくなる前にプロジェクト内での CMakeLists.txt や package.xml のコーディングスタイルを取り決めておきたい

ローカルでの幾つかの実験の成果を取り込みたいけど無遠慮に改造していいのかわからん。

**Comment by yamacir-kit** [comment]
名前が無秩序に長くなるのを防ぐため、名前空間ないしはディレクトリ構造を早い内に命名則に取り込む必要もあると思われ

**Comment by forno** [comment]
package構造案を出すのです……。
別段無駄に長いとは思わないけど、最終的にはcatkinのパッケージ名(これに名前空間やディレクトリ構造が効くのなら誰も文句は言わない)がぶつからなければいいです。
はいそこ適当に名前つけても衝突しないとか言わない。

名称を変えるのはbranch切ってから各packageごとに名称変更手続き(directory, package.xml, CMakeLists.txt, 各依存先全ての依存名変更, pull-request送信)を行えば安全にできるかと思います。
面倒なので特にしたくはありません。

現在、map/developが実はマージできそうな感じです。実装がまだまだ汚いのが気になりますが、最低限は動くでしょう。
これをマージして速やかにパッケージリネームに入るのもありです。

**Comment by forno** [comment]
ちなみにrosシステムはopt内+1つのworkspace内のパッケージを `source setup.bash` によってキャッシュしています。

その中でパッケージ名さえ被らなければ、rosのコマンドは一切移動せずににpackage名を指定してファイルを編修、移動、コピー、実行できるので、それができたら私的に何もいうことは無いです。

**Comment by yamacir-kit** [comment]
考えなおしてみたら名前を付け直す必要はなさそうなので命名則の話は無かったことにして下さい。
名前を付け直したいパッケージは幾つか有りますが（たいてい俺が作ったやつです）、大部分が改善版ないしはよりコンパクトな新パッケージによって存在意義を失うと思われるので消すまで放置します。

**Comment by yamacir-kit** [comment]
コーディングスタイルに関しては新規はともかく既存のものを弄る際は元のルールに従う形でやるわ。

正直issueするような話題じゃなかった。
すまぬ。
